### ISSUE TITLE
Geography Taxonomy

### ISSUE THREAD

**Issue by simanadler** [IBM/the-mesh-for-data#146]
|   |   |
| - | - |
| Design doc | https://ibm.box.com/s/62xh8iwu64aas4awb2fwtad8betn1e07 |
| Parent issue | #144  |
| Required issues | # |

# Description

In a multi-cluster environment it is important to map the clusters to the geography in which they run, AND to ensure that the geography related policies defined in the policy manager relate to the same policies.  Thus a policy taxonomy is required.

# Requirements

1. Create a common taxonomy for geographies to be used by the M4D multi-cluster management and by the policies in the policy manager.
2. k8s has 2 types of topology labels zone/region.  Determine if we need both.

**Comment by roee88** [comment]
As a general rule of thumb, all taxonomies should be handled as configuration rather than being hard coded in the core of the project. Even if a connectors and modules stack is developed against a specific taxonomy. 

Specifically to geographies, I'm asking some initial questions to better understand how a taxonomy for geographies could be implemented and what is the actual added value of having it:

In what way would it be enforced? Is it a validation that no policy exists that refers to unknown location? Is it validation that no cluster is created in an unknown geo? 

In what level is it defined? Do we as a project define this taxonomy as configuration? Is it defined at the policy manager connector level instead? Who populates it?

**Comment by roee88** [comment]
To be considered as part of https://github.com/IBM/the-mesh-for-data/issues/238
