### ISSUE TITLE
Minimizing manager's rbac capabilities

### ISSUE THREAD

**Issue by tomersolomon1** [IBM/the-mesh-for-data#20]
#### Problem
The manager needs many rbac capabilities. In particular, it creates new namespaces and in these it needs to instantiate modules, control the network policies, etc. In essence, the manager needs "administrator" permissions in the namespaces it creates.
However, these namespaces are not known in advance, as they are created during the lifecycle of the `M4DApplication` CRDs, etc. 
Therefore, during the installation of the manager we can't restrict its capabilities to only a certain set of namespaces by creating the relevant RBAC roles / rolebindings inside them.

Instead, the current solution is to create a `clusterrole` and a `clusterrolebinding` which grants the manager an "allow-all" capability in the entire cluster. However, this isn't the ideal solution, as it gives the manager capabilities over namespaces which it has nothing to do with.

#### Proposed Solution
Use HNC: https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc

In particular, every time the manager wants to spawn a new namespace, it creates a `SubnamespaceAnchor` resource. This resource handles the creation of new a namespace, and also propagates the rbac resources from the parent namespace to the subnamespace. Now, in the namespace `m4d-system` we create a role + rolebinding (or just create a clusterrole and a rolebinding) for granting the manager "allow-all" capabilities. Since the rbac resources are propagated to the subnamespace, this means the manager will have these capabilities in the subnamespaces as well - but not over the entire cluster.

**Comment by roee88** [comment]
Any thoughts on how this changes in a multicluster setting? 

It seems like the manager in coordinator cluster will not need special rbac anyway but it will always be privileged to do anything (delegated to Razee). 

For the manager in remote clusters (basically the blueprint controller) I guess that rbac resources can be pushed from the coordinator cluster directly, right?

**Comment by roee88** [comment]
@froesef suggested to have a single namespace for all blueprints of a cluster, rather than creating one for each blueprint. This would reduce the noise on the cluster. We will need to ensure that it has no implications on https://github.com/IBM/the-mesh-for-data/issues/56 and also consider the introduction of application isolation in the future. 

However, assuming we do it that way then the manager of a remote cluster needs RBAC to the blueprints namespace. In that case the manager controllers in a remote should probably be namespace scoped. 

For the coordinator, there is the additional application controller but its RBAC is straight forward and there's the plotter controller that depends on the cluster manager (with Razee no RBAC is used).

**Comment by roee88** [comment]
Replaced with https://github.com/IBM/the-mesh-for-data/issues/304
