### ISSUE TITLE
manager: remove the use of `docker-credentials` secret

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#210]
The manager makefile [creates a secret](https://github.com/IBM/the-mesh-for-data/blob/9bd719b8bf3aad70ed639f21e7abe0b200c93ddc/manager/Makefile#L144) holding docker credentials for the defined DOCKER_HOSTNAME/DOCKER_NAMESPACE.

This secret is used in a kustomize [patch](https://github.com/IBM/the-mesh-for-data/blob/66ad6519240ba5bb32322986ab79a802513e44fb/manager/config/default/manager_environment_patch.yaml) that is part of default. It loads the secret values into the manager as environment variables DOCKER_HOSTNAME, DOCKER_NAMESPACE, DOCKER_TAGNAME, DOCKER_PASSWORD, and DOCKER_USERNAME.

These values are then used for two different purposes:
1. The motion controller webhooks uses them as fallback when MOVER_IMAGE is not defined
2. The blueprint controller uses them to login to any OCI registry for pulling helm charts

Following https://github.com/IBM/the-mesh-for-data/issues/83, the suggestion is to:
1. Remove these from motion controller webhooks - @froesef are we really using it?
2. Remove these from blueprint controller (removes the half-baked support for pulling from private helm repos)
3. Remove the creation of this secret from the makefiles 

Introducing support for pulling helm chart from a registry that requires authentication should be a separate feature and we will get to it when there will be a concrete requirement for that.

**Comment by froesef** [comment]
I'm ok with dropping the DOCKER_NAMESPACE, DOCKER_TAGNAME variables. The image of a module can be fixed in many different ways. We don't need yet another way. (That's for the motion controller webhooks)

About the credentials it depends if we want to support the use case when e.g. someone has a custom module that should be supported from a private registry. (In that case we would need to log in to that registry some way) If we can do it through docker credentials that belong to the service account that's fine with me to remove these credentials.

About the docker secret creation that also comes back to supporting custom images in a custom registry. Also for e.g. the images of the manager or other components. (Although we could view this as a special case and leave this exercise to the admin that installs the mesh)

**Comment by roee88** [comment]
> About the credentials it depends if we want to support the use case when e.g. someone has a custom module that should be supported from a private registry. (In that case we would need to log in to that registry some way) If we can do it through docker credentials that belong to the service account that's fine with me to remove these credentials.

Abusing DOCKER_NAMESPACE etc for this purpose was not a good choice. We should not tie the registry used by a module to the registry we use for our images. what if it's a different private registry? what if there are multiple different private registries? Like I wrote, if this will actually be needed then we would open a separate discussion to design the solution.

> About the docker secret creation that also comes back to supporting custom images in a custom registry. Also for e.g. the images of the manager or other components. (Although we could view this as a special case and leave this exercise to the admin that installs the mesh)

I'm fine with keeping this but making this optional and explicit. As you might remember, we encountered issues where the existence of this secret blocked access to public registries (due to wrong values defined in the machine of whoever deployed it, but still weird stuff can happen).
