### ISSUE TITLE
multicluster: Support for cluster groups

### ISSUE THREAD

**Issue by froesef** [IBM/the-mesh-for-data#376]
At the moment the multi cluster setup will use all clusters registered with Razee and have a certain configuration file installed. This means that we can only support one mesh instance per Razee instance. This might be troublesome when e.g. using larger Razee setups. 
I propose to introduce a field in the `cluster-metadata` config map that helps to distinguish setups.
What do you think about a field `MeshName`. So that we would have a config map like this:
```
MeshName: "dev-mesh-1"
ClusterName: "mycluster"
Region: "region1"
Zone: "zone1"
```

The mesh name would also be specified in the `m4d-config` so that the controller cluster knows in which mesh it is. Or we could mount the `cluster-metadata` map for the manager.

**Comment by roee88** [comment]
Interesting topic. Should we convert it into a discussion?

> This might be troublesome when e.g. using larger Razee setups.

I understand it from a technology perspective, but not yet from a use case perspective. Ideally we should come up with a set of deployment models according to requirements (we got questions even about multiple managers in the same cluster). But that's not necessarily  a blocker from making progress here.

Anyway, `cluster-metadata` is actually very Razee specific already. I don't know any other tool that reads remote configmaps like that.

Introducing MeshName sounds like additional complexity because we don't have a name for a manager deployment already. I'm also unsure about making it configurable from the remote, but that's minor and I have seen such models being used (e.g. in Kuma). How about sticking to what Razee provides? Setup a cluster group in Razee with all the worker clusters. In a later stage we can even use this group for other purposes like installing/updating our controllers.
